{{ if and .Values.dags.gitSync.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}-git-credentials
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  GITSYNC_USERNAME: {{ default "" .Values.dags.gitSync.gitUserName | b64enc }}
  GITSYNC_PASSWORD: {{ default "" .Values.dags.gitSync.gitPassword | b64enc }}
  GIT_SYNC_USERNAME: {{ default "" .Values.dags.gitSync.gitUserName | b64enc }}
  GIT_SYNC_PASSWORD: {{ default "" .Values.dags.gitSync.gitPassword | b64enc }}
{{- end }}
